on:
  push:
    branches:
      - master
  pull_request:

name: Check CMake install

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - uses: actions/cache@v4
      id: cache
      with:
        path: libtiledb
        key: tiledb-2.26.2

    - name: Install TileDB
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        sudo apt-get install wget
        mkdir libtiledb
        cd libtiledb
        wget https://github.com/TileDB-Inc/TileDB/releases/download/2.26.2/tiledb-linux-x86_64-2.26.2-30fc114.tar.gz -O tiledb.tar.gz
        tar -xvf tiledb.tar.gz

    - name: Configure the build
      run: cmake -S . -B build -DTATAMI_TILEDB_TESTS=OFF -DCMAKE_PREFIX_PATH=libtiledb

    - name: Install the library
      run: sudo cmake --install build

    - name: Test downstream usage
      run: |
        mkdir _downstream
        touch _downstream/source.cpp
        cat << EOF > _downstream/CMakeLists.txt
        cmake_minimum_required(VERSION 3.24)
        project(test_install)
        add_executable(whee source.cpp)
        find_package(tatami_tatami_tiledb)
        target_link_libraries(whee tatami::tatami_tiledb)
        EOF

        wd=$(pwd)
        cd _downstream && cmake -S . -B build -DCMAKE_PREFIX_PATH=${wd}/libtiledb
