on:
  push:
    branches:
      - master
  pull_request:

name: Check CMake install

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Install tatami_chunked
      run: |
        git clone https://github.com/tatami-inc/tatami_chunked dep-tatami_chunked --depth=1
        cd dep-tatami_chunked
        cmake -S . -B build -DTATAMI_CHUNKED_TESTS=OFF
        sudo cmake --install build

    - uses: actions/cache@v3
      id: cache
      with:
        path: libtiledb
        key: tiledb-2.15.3

    - name: Install TileDB
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        sudo apt-get install wget
        mkdir libtiledb
        cd libtiledb
        wget https://github.com/TileDB-Inc/TileDB/releases/download/2.15.3/tiledb-linux-x86_64-2.15.3-689bea0.tar.gz -O tiledb.tar.gz
        tar -xvf tiledb.tar.gz

    - name: Configure the build
      run: cmake -S . -B build -DTATAMI_TILEDB_FETCH_EXTERN=OFF -DTATAMI_TILEDB_TESTS=OFF -DCMAKE_PREFIX_PATH=libtiledb

    - name: Install the library
      run: sudo cmake --install build

    - name: Test downstream usage
      run: |
        mkdir _downstream
        touch _downstream/source.cpp
        cat << EOF > _downstream/CMakeLists.txt
        cmake_minimum_required(VERSION 3.24)
        project(test_install)
        add_executable(whee source.cpp)
        find_package(tatami_tatami_tiledb)
        target_link_libraries(whee tatami::tatami_tiledb)
        EOF
        cd _downstream && cmake -S . -B build
